name: Docker Prune

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  prune:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: reverse_proxy
      NUM_IMAGES_TO_KEEP: 5

    steps:
      - uses: actions/checkout@v6

      - name: Get images
        run: |
          curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$IMAGE_NAME/versions?per_page=100" \
            > "$IMAGE_NAME.versions.json"

      - name: Delete old versions
        run: |
          IDS=($(jq -r 'sort_by(.created_at) | reverse | .[].id' "${IMAGE_NAME}.versions.json"))

          TOTAL=${#IDS[@]}
          START=$NUM_IMAGES_TO_KEEP

          if [ $TOTAL -le $NUM_IMAGES_TO_KEEP ]; then
              echo "Nothing to delete for $IMAGE_NAME."
              exit 0
          fi

          echo "Keeping latest $NUM_IMAGES_TO_KEEP versions for $IMAGE_NAME, deleting $((TOTAL-NUM_IMAGES_TO_KEEP)) old versions."
          for ((i=START; i<TOTAL; i++)); do
            VERSION_ID=${IDS[$i]}
            echo "Deleting version ID: $VERSION_ID"

            curl -s -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/users/${{ github.repository_owner }}/packages/container/${IMAGE_NAME}/versions/$VERSION_ID"
          done
